[project]
name = "regulation-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llama-index>=0.14.10",
    "llama-index-llms-openai",
    "llama-index-llms-openai-like>=0.5.3",
    "llama-index-llms-gemini",
    "llama-index-llms-openrouter",
    "llama-index-llms-ollama",
    "beautifulsoup4",
    "markdownify>=1.2.2",
    "olefile",
    "pandas",
    "pyhwp>=0.1b15",
    "python-dotenv>=1.2.1",
    "questionary>=2.1.1",
    "rich>=14.2.0",
]
