moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.8.1
project:
  name: regulation_manager
  mode: personal
  description: ''
  created_at: '2026-01-24 14:36:06'
  template_version: 1.8.1
  optimized: false
